const $=s=>document.querySelector(s);let prepared={items:[]},status={},active=null;
async function json(p){const r=await fetch(p+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(p);return r.json()}
function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
async function load(){try{[prepared,status]=await Promise.all([json('./prepared.json'),json('./status.json')]);render()}catch(e){$('#stamp').textContent='Error al actualizar';}}
function render(){const items=[...(prepared.items||[])].sort((a,b)=>{const ac=status.events?.[a.event_id]?.source_count||a.drafted_source_count||0,bc=status.events?.[b.event_id]?.source_count||b.drafted_source_count||0;return bc-ac||String(b.prepared_at||'').localeCompare(String(a.prepared_at||''))});
$('#ready').textContent=items.length;$('#processing').textContent=status.processing_count??0;$('#three').textContent=status.three_sources_count??0;$('#stamp').textContent='Actualizado '+new Date(status.updated_at||prepared.updated_at||Date.now()).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'});$('#health').textContent=(status.healthy_source_count??'–')+' fuentes generales sanas';
const list=$('#list');list.innerHTML='';if(!items.length){list.innerHTML='<div class="empty">No hay noticias redactadas pendientes.</div>';return}
for(const x of items){const n=$('#card').content.cloneNode(true),card=n.querySelector('.card'),cur=status.events?.[x.event_id]?.source_count??x.drafted_source_count??0,draft=x.drafted_source_count??cur;n.querySelector('.title').textContent=x.title||'Sin titular';n.querySelector('.meta').textContent='Redactada con '+draft+' ('+cur+') · '+(x.prepared_at?new Date(x.prepared_at).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'}):'');n.querySelector('.facts').textContent=x.factual_summary||'';const vs=n.querySelector('.variants');for(const v of x.variants||[]){const d=document.createElement('div');d.className='variant';d.innerHTML='<strong>'+esc(v.label||'Opción')+'</strong><p>'+esc(v.text||'')+'</p><a target="_blank" rel="noopener" href="'+esc(v.url||('#'))+'">Publicar en X</a>';vs.appendChild(d)}n.querySelector('.summary').onclick=()=>card.classList.toggle('open');n.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>act(b.dataset.act,x));list.appendChild(n)}}
async function act(action,x){if(action==='rewrite'){active=x;$('#rewriteText').value='';$('#rewriteDlg').showModal();return}await send(action,x,'')}
async function send(action,x,instructions){const r=await fetch('/api/ttittulares-control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,event_id:x.event_id,instructions})});if(!r.ok){alert('No se pudo guardar la acción');return}await load()}
$('#rewriteOk').onclick=async e=>{e.preventDefault();const t=$('#rewriteText').value.trim();if(!t)return;$('#rewriteDlg').close();await send('rewrite',active,t)};$('#refresh').onclick=load;load();setInterval(load,60000);